# Generated by Django 4.2 on 2023-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_tishki_description_tishki_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tishki',
            name='fileId',
            field=models.IntegerField(default=1),
        ),
    ]
