# Generated by Django 4.2 on 2023-06-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_tishki_fileid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tishki',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tishki',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tishki',
            name='size',
        ),
    ]
