# Generated by Django 4.2 on 2023-06-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_tishki_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tishki',
            name='photo',
            field=models.TextField(default='https://lh3.googleusercontent.com/1ngFfo9Xjg4K5zUd46YxfUCE8VKcsTAKvy2zyUW5tI2wqYKIZMMI9RY8vdeY64JqoOMG1od13l1xDWkKyeHSzV0TktcdlvcVxXlMKHBbw4B1x9-ermtU0Fio1O-sgcc6t9DnfgFnGGm-GlkrVx8xjgxtXmHOkZ54yCtVYF'),
        ),
    ]
